### ISSUE TITLE
是否不支持WebSockets？是否可以考虑支持

### ISSUE THREAD

**Issue by ndj888** [keaixiaou/zapi#2]
# line:66 call:0 error message:client must instanceof ZPHP\Socket\Callback\SwooleWebSocket      file:/usr/src/myapp/vend
or/keaixiaou/zphp/ZPHP/Socket/Adapter/Swoole.php
#0 line:32 call:ZPHP\Socket\Adapter\Swoole->setClient   file:/usr/src/myapp/vendor/keaixiaou/zphp/ZPHP/Server/Adapter/So
cket.php
#1 line:258 call:ZPHP\Server\Adapter\Socket->run        file:/usr/src/myapp/vendor/keaixiaou/zphp/ZPHP/ZPHP.php
#2 line:231 call:ZPHP\ZPHP::start       file:/usr/src/myapp/vendor/keaixiaou/zphp/ZPHP/ZPHP.php
#3 line:222 call:ZPHP\ZPHP::doCommand   file:/usr/src/myapp/vendor/keaixiaou/zphp/ZPHP/ZPHP.php
#4 line:10 call:ZPHP\ZPHP::run  file:/usr/src/myapp/webroot/main.php

**Comment by keaixiaou** [comment]
暂时没有支持websocket，以后会考虑

**Comment by keaixiaou** [comment]
最新版的已经支持了
