### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by loyating** [keaixiaou/zapi#4]
PHP Warning:  swoole_mysql::query(): Query is empty. in /media/sf_work/fcdhweb/fcdh_log_api/vendor/keaixiaou/zphp/ZPHP/Coroutine/Mysql/MysqlAsynPool.php on line 154

服务启动时候 。。 参数为NULL导致。。
在一个：配置文件参数在你的示例中不齐全，读取时候也没有默认值，导致warning。。

**Comment by keaixiaou** [comment]
你怎么使用，业务代码呢

**Comment by loyating** [comment]
git拉取代码  composer 获取依赖
修改了MySQL配置文件
php main.php start 
日志中就会出现如下：
PHP Warning:  swoole_mysql::query(): Query is empty. in $vendor/keaixiaou/zphp/ZPHP/Coroutine/Mysql/MysqlAsynPool.php on line 154
PHP Notice:  Undefined index: token in $vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 87
PHP Notice:  Undefined index:  in $vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 87
PHP Notice:  Undefined index: token in $vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 88

没有发起任何请求，只是在启动时候报出的warning

**Comment by loyating** [comment]
app 配置文件中 single_task_worker_num  逻辑中获取时候没有给默认值

**Comment by keaixiaou** [comment]
single_task_worker_num的确有警告，已经修复，但是你上面说的swoole_mysql::query(): Query is empty没碰到，你的mysql配置看一下，还有你的业务代码怎么写的，看一下

**Comment by loyating** [comment]
ZPHP\Coroutine\Mysql\MysqlAsynPool
/**
     * 执行mysql命令
     * @param $data
     */
    public function execute($data)
    {
//        if(!is_array($data))
//            return false;
//上面两行是我自己加的判断，打印是null值

MySQL配置：
return [
    'mysql'=>[
        'host' => '127.0.0.1',
        'port' => 3306,
        'user' => 'root',
        'password' => 'test__2017',
        'database' => 'fcdhex',
        'asyn_max_count' => 1,
        'start_count' => 1,
    ],
];


git下来只修改了MySQL配置想跑一下看看，业务代码没有更改过
感觉是初始化建立连接那里。 start_count 

PHP Warning:  swoole_mysql::query(): Query is empty. in /media/sf_work/fcdhweb/fcdh_log_api/vendor/keaixiaou/zphp/ZPHP/Coroutine/Mysql/MysqlAsynPool.php on line 156
PHP Notice:  Undefined index: token in /media/sf_work/fcdhweb/fcdh_log_api/vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 87
PHP Notice:  Undefined index:  in /media/sf_work/fcdhweb/fcdh_log_api/vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 87
PHP Notice:  Undefined index: token in /media/sf_work/fcdhweb/fcdh_log_api/vendor/keaixiaou/zphp/ZPHP/Coroutine/Pool/AsynPool.php on line 88
2017-03-17 10:27:17.49243200 ERROR-Coroutine Exception:执行sql[]失败

**Comment by loyating** [comment]
18010097210 我的QQ
或者留一下你的？

**Comment by keaixiaou** [comment]
QQ群-384013097，估计你readme和开发手册都没看的

**Comment by keaixiaou** [comment]
已经修复了，之前代码重构导致的，重新composer update 依赖框架一下。
thanks
